In [1]:
pip install xgboost lightgbm

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Note: you may need to restart the kernel to use updated packages.


In [8]:
import boto3
import pandas as pd; pd.set_option('display.max_columns', 100)
import numpy as np

import matplotlib.pyplot as plt; plt.style.use('ggplot')
import seaborn as sns

from scipy.stats import rankdata
from sklearn.multiclass import OneVsRestClassifier
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold, train_test_split, GridSearchCV, StratifiedKFold, TimeSeriesSplit
from sklearn.metrics import mean_squared_error, roc_auc_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier, HistGradientBoostingRegressor
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier, LGBMRegressor 
from xgboost import XGBClassifier, XGBRegressor
from catboost import CatBoostClassifier, CatBoostRegressor

import optuna 

s3 = boto3.resource('s3')
bucket_name = 'analytics-data-science-competitions'
bucket = s3.Bucket(bucket_name)

file_key_1 = 'March-Mania-2023/Evan-Data/MNCAA_train_538.csv'
file_key_2 = 'March-Mania-2023/Evan-Data/MNCAA_test_538.csv'
file_key_3 = 'March-Mania-2023/Evan-Data/WNCAA_train_538.csv'
file_key_4 = 'March-Mania-2023/Evan-Data/WNCAA_test_538.csv'

bucket_object_1 = bucket.Object(file_key_1)
file_object_1 = bucket_object_1.get()
file_content_stream_1 = file_object_1.get('Body')

bucket_object_2 = bucket.Object(file_key_2)
file_object_2 = bucket_object_2.get()
file_content_stream_2 = file_object_2.get('Body')

bucket_object_3 = bucket.Object(file_key_3)
file_object_3 = bucket_object_3.get()
file_content_stream_3 = file_object_3.get('Body')

bucket_object_4 = bucket.Object(file_key_4)
file_object_4 = bucket_object_4.get()
file_content_stream_4 = file_object_4.get('Body')

## Reading data files
man_train = pd.read_csv(file_content_stream_1)
# man_test = pd.read_csv(file_content_stream_2)
woman_train = pd.read_csv(file_content_stream_3)
# woman_test = pd.read_csv(file_content_stream_4)

man_train['target'] = np.where(man_train['ResultDiff'] > 0, 1, 0)
man_train = man_train[man_train['Season'] >= 2016].reset_index(drop = True)

woman_train['target'] = np.where(woman_train['ResultDiff'] > 0, 1, 0)
woman_train = woman_train[woman_train['Season'] >= 2016].reset_index(drop = True)

man_test = pd.read_csv('man_test_tour_phase_1.csv')
woman_test = pd.read_csv('woman_test_tour_phase_1.csv')

# Man

In [12]:
to_select = ['X1_WinRatio14d',
             'X1_PointsMean',
             'X1_PointsMedian',
             'X1_PointsDiffMean',
             'X1_FgaMean',
             'X1_FgaMedian',
             'X1_FgaMin',
             'X1_FgaMax',
             'X1_AstMean',
             'X1_BlkMean',
             'X1_OppFgaMean',
             'X1_OppFgaMin',
             'X1_EfgpMean',
             'X1_PossessionsMean',
             'X1_PpmMean',
             'X1_FtrMean',
             'X1_TopMean',
             'X1_DrebpMean',
             'X2_WinRatio14d',
             'X2_PointsMean',
             'X2_PointsMedian',
             'X2_PointsDiffMean',
             'X2_FgaMean',
             'X2_FgaMedian',
             'X2_FgaMin',
             'X2_FgaMax',
             'X2_AstMean',
             'X2_BlkMean',
             'X2_OppFgaMean',
             'X2_OppFgaMin',
             'X2_EfgpMean',
             'X2_PossessionsMean',
             'X2_PpmMean',
             'X2_FtrMean',
             'X2_TopMean',
             'X2_DrebpMean',
             'Seed1',
             'Seed2',
             'SeedDiff',
             'quality_march_T1',
             'quality_march_T2', 
             'ResultDiff',
             'X1_team_rating',
             'X1_rd1_win',
             'X1_rd2_win',
             'X1_rd3_win',
             'X1_rd4_win',
             'X1_rd5_win',
             'X1_rd6_win',
             'X1_rd7_win',
             'X2_team_rating',
             'X2_rd1_win',
             'X2_rd2_win',
             'X2_rd3_win',
             'X2_rd4_win',
             'X2_rd5_win',
             'X2_rd6_win',
             'X2_rd7_win']

X = man_train[to_select]
Y = man_train['target']

man_test_tour_ID = man_test['ID']
man_test_tour = man_test[to_select]

In [15]:
man_test_tour

X1_WinRatio14d  X1_PointsMean  X1_PointsMedian  X1_PointsDiffMean  \
0               0.80      82.176471             80.0          13.676471   
1               0.80      82.176471             80.0          13.676471   
2               0.80      82.176471             80.0          13.676471   
3               0.80      82.176471             80.0          13.676471   
4               0.80      82.176471             80.0          13.676471   
...              ...            ...              ...                ...   
2273            1.00      72.156250             74.0           5.437500   
2274            1.00      72.156250             74.0           5.437500   
2275            0.80      67.812500             67.5           7.562500   
2276            0.80      67.812500             67.5           7.562500   
2277            0.75      76.303030             76.0           5.272727   

      X1_FgaMean  X1_FgaMedian  X1_FgaMin  X1_FgaMax  X1_AstMean  X1_BlkMean  \
0      62.205882          63.0         48         90   15.205882    5.058824   
1      62.205882          63.0         48         90   15.205882    5.058824   
2      62.205882          63.0         48         90   15.205882    5.058824   
3      62.205882          63.0         48         90   15.205882    5.058824   
4      62.205882          63.0         48         90   15.205882    5.058824   
...          ...           ...        ...        ...         ...         ...   
2273   55.562500          55.5         46         69   13.656250    2.937500   
2274   55.562500          55.5         46         69   13.656250    2.937500   
2275   53.468750          52.5         45         68   15.812500    4.218750   
2276   53.468750          52.5         45         68   15.812500    4.218750   
2277   57.484848          57.0         50         67   13.151515    3.090909   

      X1_OppFgaMean  X1_OppFgaMin  X1_EfgpMean  X1_PossessionsMean  \
0         64.382353            53     0.528760           75.384559   
1         64.382353            53     0.528760           75.384559   
2         64.382353            53     0.528760           75.384559   
3         64.382353            53     0.528760           75.384559   
4         64.382353            53     0.528760           75.384559   
...             ...           ...          ...                 ...   
2273      55.156250            47     0.550682           66.652344   
2274      55.156250            47     0.550682           66.652344   
2275      51.906250            41     0.514286           63.428906   
2276      51.906250            41     0.514286           63.428906   
2277      54.909091            42     0.517366           70.899242   

      X1_PpmMean  X1_FtrMean  X1_TopMean  X1_DrebpMean  X2_WinRatio14d  \
0       1.884614    0.275133    0.179410      0.740689        0.800000   
1       1.884614    0.275133    0.179410      0.740689        0.400000   
2       1.884614    0.275133    0.179410      0.740689        0.250000   
3       1.884614    0.275133    0.179410      0.740689        0.333333   
4       1.884614    0.275133    0.179410      0.740689        0.333333   
...          ...         ...         ...           ...             ...   
2273    1.666309    0.201526    0.132953      0.764322        0.750000   
2274    1.666309    0.201526    0.132953      0.764322        0.800000   
2275    1.585723    0.250737    0.127736      0.749173        0.750000   
2276    1.585723    0.250737    0.127736      0.749173        0.800000   
2277    1.772481    0.297621    0.174426      0.720425        0.800000   

      X2_PointsMean  X2_PointsMedian  X2_PointsDiffMean  X2_FgaMean  \
0         82.676471             84.5          11.176471   59.264706   
1         70.323529             68.5           2.617647   60.470588   
2         74.424242             76.0           7.030303   56.909091   
3         72.718750             72.0           5.656250   58.593750   
4         77.156250             77.0           6.906250   5

In [20]:
#############
## XGBoost ##
#############

xgb_params = pd.read_csv('man_XGB_Phase_2_42_Optuna_Hyperparameters.csv')

xgb_md = XGBClassifier(tree_method = 'hist', 
                       max_depth = xgb_params['max_depth'][0],
                       learning_rate = xgb_params['learning_rate'][0],
                       n_estimators = xgb_params['n_estimators'][0],
                       gamma = xgb_params['gamma'][0],
                       min_child_weight = xgb_params['min_child_weight'][0],
                       colsample_bytree = xgb_params['colsample_bytree'][0],
                       subsample = xgb_params['subsample'][0]).fit(X, Y)

xgb_pred = xgb_md.predict_proba(man_test_tour)[:, 1]

##############
## LightGBM ##
##############

lgb_params = pd.read_csv('man_LightGBM_Phase_2_42_Optuna_Hyperparameters.csv')

lgb_md = LGBMClassifier(boosting_type = 'gbdt', 
                        n_estimators = lgb_params['n_estimators'][0],
                        learning_rate = lgb_params['learning_rate'][0],
                        max_depth = lgb_params['max_depth'][0],
                        lambda_l1 = lgb_params['lambda_l1'][0],
                        lambda_l2 = lgb_params['lambda_l2'][0],
                        num_leaves = lgb_params['num_leaves'][0],
                        bagging_fraction = lgb_params['bagging_fraction'][0],
                        feature_fraction = lgb_params['feature_fraction'][0]).fit(X, Y)

lgb_pred = lgb_md.predict_proba(man_test_tour)[:, 1]

##################
## HistGradient ##
##################

hist_params = pd.read_csv('man_Hist_Phase_1_42_Optuna_Hyperparameters.csv')

hist_md = HistGradientBoostingClassifier(l2_regularization = hist_params['l2_regularization'][0],
                                         early_stopping = False,
                                         learning_rate = hist_params['learning_rate'][0],
                                         max_iter = hist_params['max_iter'][0],
                                         max_depth = hist_params['max_depth'][0],
                                         max_bins = hist_params['max_bins'][0],
                                         min_samples_leaf = hist_params['min_samples_leaf'][0],
                                         max_leaf_nodes = hist_params['max_leaf_nodes'][0]).fit(X, Y)

hist_pred = hist_md.predict_proba(man_test_tour)[:, 1]

[LightGBM] [Warning] lambda_l1 is set=0.2260228224184179, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.2260228224184179
[LightGBM] [Warning] feature_fraction is set=0.749437638037727, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.749437638037727
[LightGBM] [Warning] lambda_l2 is set=2.6940257639572143, reg_lambda=0.0 will be ignored. Current value: lambda_l2=2.6940257639572143
[LightGBM] [Warning] bagging_fraction is set=0.5844471963342652, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5844471963342652


In [18]:
xgb_pred

array([0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5], dtype=float32)

In [19]:
lgb_pred

array([0.99941535, 0.99947264, 0.99947264, ..., 0.99947264, 0.99936685,
       0.9993514 ])

In [21]:
hist_pred

array([0.9665203, 0.9665203, 0.9665203, ..., 0.9665203, 0.9665203,
       0.9665203])